In [14]:
##Import All Necessary libraries
import tensorflow as tf
import numpy as np
import pandas as pd
import cv2
import glob
import glob
import random
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import *
from tensorflow.keras.models import *
from tensorflow.keras.callbacks import *
from tensorflow.keras import backend as K
from tensorflow.keras.utils import *
from tensorflow.keras.regularizers import *

In [2]:
###Create data loader for images
from glob import glob
data_im = np.sort( np.array(glob('C:/Users/anikr/Computer Vison/Class 6 -Code/Assignment 1/Image/*'))) 

In [8]:
##Create function for extract image and corresponding labels from dataset

def all_data_dir(data):
    
    img = list()
    labels = list()

    for j in range(len(data)//1):
    #vdr = datat[j]
        im = np.sort( np.array(glob( data[j]+'/*')))  
        random.shuffle(im)
 
        
        for i in range(len(im)//1):
 
            img.append(im[i]) 
            labels.append(j) 

                
    return np.array(img),np.array(labels)

In [9]:
##generate image data and labels
image,label=all_data_dir(data_im)

In [10]:
###determine class number
n_cls = np.max(label)+1
print(n_cls)

6


# Generate image into pixels array and binary labels

In [15]:
##function for determine image batch size , height , width & labels

def image_data_loader(data_path, labels, batch_size, n_class, shuffle=True, toption=True):
    num_samples = len(data_path)
    pairs = list(zip(data_path, labels))

    if shuffle:
        random.shuffle(pairs)

    for offset in range(0, num_samples, batch_size):
        image_batch = np.array(pairs[offset:offset+batch_size])[:, 0]
        label_batch = np.array(pairs[offset:offset+batch_size])[:, 1]

        X_train = []
        y_train = []

        for (image_path, label) in zip(image_batch, label_batch):
            if str(label.dtype) == '<U9':
                label = label
            else:
                label = to_categorical(label, n_class)

            image = cv2.imread(image_path)
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) / 255
            image = tf.image.resize(image, [128, 128])

            X_train.append(image)
            y_train.append(label)

        X_train = np.array(X_train)
        y_train = np.array(y_train)

        yield X_train, y_train

In [16]:
img_data=image_data_loader(image, label, 10 , n_cls, shuffle=True, toption=True)

In [17]:
x,y=next(iter(img_data))

In [18]:
print(x.shape,y.shape)

(10, 128, 128, 3) (10, 6)


In [19]:
print(x[0],y[0])

[[[0.02500575 0.3100818  0.30339476]
  [0.01136092 0.3087496  0.29597026]
  [0.02583463 0.29560095 0.283099  ]
  ...
  [0.02292672 0.2628011  0.26282316]
  [0.1558187  0.38836718 0.3629842 ]
  [0.04032341 0.23917213 0.2650441 ]]

 [[0.07057483 0.3055851  0.29660478]
  [0.07021533 0.2821775  0.3046607 ]
  [0.04418371 0.28927436 0.32425946]
  ...
  [0.05468391 0.31002057 0.28831932]
  [0.03199367 0.2916212  0.31603742]
  [0.01203685 0.2629713  0.28263324]]

 [[0.05959545 0.29506072 0.32282212]
  [0.09058264 0.3459494  0.32902497]
  [0.03096996 0.32002074 0.29525793]
  ...
  [0.02149586 0.26761812 0.2529304 ]
  [0.04295343 0.26051602 0.26837757]
  [0.03905053 0.28361243 0.2606005 ]]

 ...

 [[0.9078982  1.         0.9797294 ]
  [0.95053923 0.9910281  0.9895764 ]
  [0.979284   0.9994938  0.9804235 ]
  ...
  [0.7126628  0.6586333  0.60986096]
  [0.6782318  0.65345675 0.581015  ]
  [0.6515051  0.6250539  0.5759603 ]]

 [[0.9989854  0.99585223 0.99925035]
  [0.99298406 0.9897841  0.99424475]
